spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis-15614.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 15614
      username: default
      password: UmZ4M0xlM3cweDV5cERHT0NzSEI3SW5SODhheGRBcVU=
      havePassword: "YES"
zuul:
  prefix: /api
  routes:
    movie-service:
      service-id: movie-service
      path: /cinema/**
    notification-service:
      service-id: notification-service
      path: /notification/**
    payment-service:
      service-id: payment-service
      path: /payment/**
    user-service:
      path: /user/**
      service-id: user-service
    recommendation-service:
      path: /recommendation/**
      service-id: recommendation-service
    schedule-service:
      path: /schedule/**
      service-id: schedule-service
    streaming-service:
      path: /streaming/**
      service-id: streaming-service
    subcription-service:
      path: /schedule/**
      service-id: subcription-service
cloudflare:
  r2:
    access-key-id: "NDg5MDEwY2MyNTc3NWY0M2IxMTMxNWRhOGM5ZThlY2Y="
    secret-access-key: "ODNjZmI2ZmMyNDg1YjJiZGJjNjUyNDc4ZWM0ZGFiNGVhNjlmNTQ2ZjM2MmRjM2Y0ODNiZmRhN2E1M2Y3ZDg2Zg=="
    bucket-name: "ekrok-cinema"
    region: "auto"
    endpoint: "https://d06c0f7e9f2d0c33fee98a0934f64d09.r2.cloudflarestorage.com"