spring:
  application:
    name: api-gateway
  messages:
    basename: messages
    encoding: UTF-8
  data:
    redis:
      host: redis-10592.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 10592
      username: default
      password: El4coajMDswliyAPvHkMR5EmpVJRhY8Z
      ssl: true
kafka:
  server-config: localhost:9092
  group-id: service
zuul:
  prefix: /api
  routes:
    cinema-service:
      service-id: cinema-service
      path: /cinema/**
    booking-service:
      service-id: booking-service
      path: /booking/**
    notification-service:
      service-id: notification-service
      path: /notification/**
    user-service:
      path: /user/**
      service-id: user-service
    discount-service:
      path: /discount/**
      service-id: discount-service
    movie-service:
      path: /movie/**
      service-id: movie-service
    schedule-service:
      path: /schedule/**
      service-id: schedule-service
    payment-service:
      path: /payment/**
      service-id: payment-service
    recommendation-service:
      path: /recommendation/**
      service-id: recommendation-service
    streaming-service:
      path: /streaming/**
      service-id: streaming-service
cloudflare:
  r2:
    access-key-id: "NDg5MDEwY2MyNTc3NWY0M2IxMTMxNWRhOGM5ZThlY2Y="
    secret-access-key: "ODNjZmI2ZmMyNDg1YjJiZGJjNjUyNDc4ZWM0ZGFiNGVhNjlmNTQ2ZjM2MmRjM2Y0ODNiZmRhN2E1M2Y3ZDg2Zg=="
    bucket-name: "ekrok-cinema"
    region: "auto"
    endpoint: "https://d06c0f7e9f2d0c33fee98a0934f64d09.r2.cloudflarestorage.com"