server:
  port: 8060

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-n69h.onrender.com/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

ribbon:
  eureka:
    enabled: true
