server:
  port: 8086

spring:
  application:
    name: movie-service

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-n69h.onrender.com/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

