server:
  port: 8083

spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-n69h.onrender.com/

management:
  tracing:
    sampling:
      probability: 1.0

