spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useSSL=true
    username: root
    password: Son191203
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
      time-to-live: 3000
  data:
    redis:
      host: redis-12995.crce185.ap-seast-1-1.ec2.redns.redis-cloud.com
      port: 12995
      username: default
      password: d3dmbFdTeE5GTDFjSU4zUFdTRDE5eG05a3FPOG9GMFg=
      havePassword: "YES"
  rest:
    notification-service:
      name: notification-service
    booking-service:
      name: booking-service
    cinema-service:
      name: cinema-service
  security:
    jwt:
      expiration_time: 1000 #hour
cloudflare:
  r2:
    access-key-id: NDg5MDEwY2MyNTc3NWY0M2IxMTMxNWRhOGM5ZThlY2Y=
    secret-access-key: ODNjZmI2ZmMyNDg1YjJiZGJjNjUyNDc4ZWM0ZGFiNGVhNjlmNTQ2ZjM2MmRjM2Y0ODNiZmRhN2E1M2Y3ZDg2Zg==
    bucket-name: ekrok-cinema
    region: auto
    endpoint: https://d06c0f7e9f2d0c33fee98a0934f64d09.r2.cloudflarestorage.com
kafka:
  server-config: localhost:9092
  group-id: service