spring:
  application:
    name: core
  messages:
    basename: messages
    encoding: UTF-8
  data:
    redis:
      host: redis-10592.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 10592
      username: default
      password: RWw0Y29hak1Ec3dsaXlBUHZIa01SNUVtcFZKUmhZOFo=
      havePassword: "YES"